# Generated by Django 4.2.28 on 2026-06-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='icon',
        ),
    ]
